package cliente;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.text.*;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/**
 *
 * @author Alejandro Campoy Nieves.
 * @author David Criado Ramón
 * 
 * La clase GUI se encarga de manejar la interacción del usuario mientras se
 * encuentre conectado en el chat.
 */
public class GUI extends JFrame {
    private ClienteTCP cliente; // Se encarga de la emisiones de datos del cliente.
    private Reader reader;
    /**
     * Inicializamos todo en el contructor
     * @param c Única instancia creada de la clase ClienteTCP (no es un singleton)
     */
    public GUI(ClienteTCP c) {
        cliente = c;
        setTitle(c.getUserName()+"@"+c.getHost());
        initComponents();
        // Desactivamos la función estándar del enter para sólo permitir usar Enter para enviar.
        texto.getInputMap().put(KeyStroke.getKeyStroke("ENTER"), "none");
        reader = new Reader(cliente, this);
    }
    
    /**
     * Pone en ejecución la hebra que cada segundo busca nuevas actualizaciones.
     * 
     */
    public void startup() {
        reader.start();
    }
    
    /**
     * Este método es utilizado por la hebra lectora para añadir el mensaje
     * recibido a la interfaz
     * @param message Mensaje a añadir en el área de chat.
     */
    public void addMessage(String message) {
        try {
            int pos = message.indexOf(":");
            String user = message.substring(0, pos + 1);
            String data = message.substring(pos + 1);
            
            /** Ponemos de un color el usuario y de otro el texto. **/
            // 1- Obtenemos el documento (Styled para poder poner colores y tal) del TextPane
            Document doc = chat.getStyledDocument();
            
            // 2 - Configuramos un color
            SimpleAttributeSet set = new SimpleAttributeSet();
            // Ponemos verde en verde y negrita
            StyleConstants.setForeground(set, Color.green);
            StyleConstants.setBold(set, true);
            
            // 3 - Insertamos el nombre de usuario
            doc.insertString(doc.getLength(), user, set);
            
            // 4 - Para el texto lo dejamos en blanco
            set = new SimpleAttributeSet();
            StyleConstants.setForeground(set, Color.white);
            
            doc.insertString(doc.getLength(), data, set);
        } catch (BadLocationException ex) {
            System.err.println(ex);
            System.err.println("Error al colocar texto en la posición indicada.");
        }
    }

    @Override
    protected void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            cliente.close();
        }
        super.processWindowEvent(e); 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        enviar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        chat.setBackground(new java.awt.Color(70, 70, 70));
        jScrollPane1.setViewportView(chat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 280));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        texto.setBackground(new java.awt.Color(156, 156, 156));
        texto.setColumns(20);
        texto.setForeground(new java.awt.Color(254, 254, 254));
        texto.setRows(5);
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(texto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 470, -1));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 120, 51));
    }// </editor-fold>//GEN-END:initComponents
    // Al pulsar enviar vaciamos el área de escritura y envimos el texto.
    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        String toSend = texto.getText();
        if (!toSend.isEmpty()) {
            cliente.sendMessage(toSend);
            addMessage(cliente.getUserName() + ": " + toSend + "\n");
            texto.setText("");
        }
    }//GEN-LAST:event_enviarActionPerformed
    // Pulsar Enter equivale a enviar.
    private void textoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            enviarActionPerformed(null);
      
    }//GEN-LAST:event_textoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane chat;
    private javax.swing.JButton enviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
