package cliente;

import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/**
 *
 * @author Alejandro Campoy Nieves.
 * @author David Criado Ramón
 * 
 * La clase GUI se encarga de manejar la interacción del usuario mientras se
 * encuentre conectado en el chat.
 */
public class GUI extends JFrame {
    private ClienteTCP cliente; // Se encarga de la emisiones de datos del cliente.
    private Reader reader;
    /**
     * Inicializamos todo en el contructor
     * @param c Única instancia creada de la clase ClienteTCP (no es un singleton)
     */
    public GUI(ClienteTCP c) {
        cliente = c;
        setTitle(c.getUserName()+"@"+c.getHost());
        initComponents();
        // Desactivamos la función estándar del enter para sólo permitir usar Enter para enviar.
        texto.getInputMap().put(KeyStroke.getKeyStroke("ENTER"), "none");
        reader = new Reader(cliente, this);
    }
    
    /**
     * Pone en ejecución la hebra que cada segundo busca nuevas actualizaciones.
     * 
     */
    public void startup() {
        reader.start();
    }
    
    /**
     * Este método es utilizado por la hebra lectora para añadir el mensaje
     * recibido a la interfaz
     * @param message Mensaje a añadir en el área de chat.
     */
    public void addMessage(String message) {
        chat.setText(chat.getText() + message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        enviar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        chat.setEditable(false);
        chat.setBackground(new java.awt.Color(76, 76, 76));
        chat.setColumns(20);
        chat.setForeground(new java.awt.Color(254, 254, 254));
        chat.setRows(5);
        jScrollPane1.setViewportView(chat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 280));

        texto.setBackground(new java.awt.Color(156, 156, 156));
        texto.setColumns(20);
        texto.setForeground(new java.awt.Color(254, 254, 254));
        texto.setRows(5);
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(texto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 470, -1));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 120, 51));
    }// </editor-fold>//GEN-END:initComponents
    // Al pulsar enviar vaciamos el área de escritura y envimos el texto.
    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        String toSend = texto.getText();
        if (!toSend.isEmpty()) {
            cliente.sendMessage(toSend);
            texto.setText("");
        }
    }//GEN-LAST:event_enviarActionPerformed
    // Pulsar Enter equivale a enviar.
    private void textoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            enviarActionPerformed(null);
      
    }//GEN-LAST:event_textoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chat;
    private javax.swing.JButton enviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
