package cliente;

/**
 *
 * @author Alejandro Campoy Nieves.
 * @author David Criado Ramón
 * 
 * La clase GUI se encarga de manejar la interacción del usuario mientras se
 * encuentre conectado en el chat.
 */
public class GUI extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        enviar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        chat.setEditable(false);
        chat.setBackground(new java.awt.Color(76, 76, 76));
        chat.setColumns(20);
        chat.setForeground(new java.awt.Color(254, 254, 254));
        chat.setRows(5);
        jScrollPane1.setViewportView(chat);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 280));

        texto.setBackground(new java.awt.Color(156, 156, 156));
        texto.setColumns(20);
        texto.setForeground(new java.awt.Color(254, 254, 254));
        texto.setRows(5);
        jScrollPane2.setViewportView(texto);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 470, -1));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 120, 51));
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chat;
    private javax.swing.JButton enviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
