package cliente;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author Alejandro Campoy Nieves.
 * @author David Criado Ramón.
 * 
 * La clase GUINombre se encarga de pedir el nombre de Usuario que va a utilizar el cliente.
 * Si son correctos se encarga de iniciar la ventana principal
 * 
 */
public class GUINombre extends JFrame{
    private ClienteTCP cliente;
    private GUI gui;
    
    /** Constructor de la GUI Nombre
     * 
     * @param c ClienteTCP que manejará la conexión que se creará sobre el host
     * y nombre de usuario obtenidos en esta clase.
     */
    public GUINombre(ClienteTCP c) {
        cliente = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        host = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre de Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 228, 30));

        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 340, -1));

        send.setText("Entrar");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel2.setText("Host");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        host.setText("localhost");
        getContentPane().add(host, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 340, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Pulsar Enter equivale a enviar
    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            sendActionPerformed(null);
    }//GEN-LAST:event_userKeyPressed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        if (cliente.setHost(host.getText())) {
            
            if (cliente.setUserName(user.getText())) {
                gui = new GUI(cliente);
                gui.startup();
                gui.pack();
                gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                gui.setLocationRelativeTo(null);
                gui.setVisible(true);
                this.dispose();
            }
            else {
                System.err.println("El nombre ya está siendo usado");
                // TO-DO Añadir información en interfaz gráfica
            }
        }
        else {
            System.err.println("No hemos podido conctactar con el host");
            // TO-DO Añadir información en la interfaz gráfica.
        }
            
    }//GEN-LAST:event_sendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField host;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton send;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
